### PR TITLE
Use post_zephir_processing submodule.

### PR DESCRIPTION
**Pull request by moseshll**
- Remove locally-hosted `bib_rights.pm` module.
- Remove locally-hosted text version of the `us_cities` data.
- Turn US cities hash into `Metadata` module variable.
- `bin/bib_newyear.pl` documentation updates.

### CODE REVIEW

**Comment by aelkiss** [comment]
FYI @jsteverman

**Comment by moseshll** [comment]
CI is having an issue because `post_zephir_processing` is a private repo. Hmmm.

**Comment by moseshll** [comment]
@aelkiss The PAT I'm using for the submodule checkout has no expiration, but it does make running the CI action dependent on my account... I think... question mark?? I note from my copy-pasta of the feed repo setup, this is not the way we should be doing it long-term.

**Comment by aelkiss** [comment]
Right, it looks like I set up an `ACCESS_TOKEN` secret in github.com/hathitrust/feed that has read access to the private submodules there; that token is tied to the @hathitrust-feed service account. We could create a separate @hathitrust-crms service account for this, perhaps? You can use an MCommunity group or alias as the email address contact. Would perhaps be worth exploring using the GitHub API for setting up and rotating PATs and repository secrets...

**Comment by moseshll** [comment]
Shall I assume that the service account is something that needs to be set up at the organization level? I think it would be wise to follow whatever `feed` is doing. I guess I'd use `crms-admin@umich.edu` as the service account for CRMS so long as we need this sorta `ACCESS_TOKEN` support in the CI.

**Comment by aelkiss** [comment]
I don't think there are any permissions issues barring you from creating that service account and granting it the appropriate permissions, but let me know if you run into any problems.

**Comment by moseshll** [comment]
@aelkiss Service account added, tests re-run using new PAT. Credentials are in the private config file.

**Review by aelkiss — COMMENTED** [review]
Looks fine to me; I'd like to make sure that @jsteverman is at least aware of this usage.

**Review by jsteverman — APPROVED** [review]
post_zeph usage noted.

**Pull request merged**
